### ISSUE TITLE
Slider Bullets

### ISSUE THREAD

**Issue by DanArpoika** [cranfordj08/verint-resources#7]
I might be wrong on this but the size looks smaller than mock

![Screen Shot 2021-06-04 at 1 26 35 PM](https://user-images.githubusercontent.com/9644069/120840735-9abf4980-c538-11eb-8ed9-e85d5b4f9133.png)

**Comment by cranfordj08** [comment]
It's 9px in the Figma and I measured with Firefox on my computer and it's also 9px there.  I did adjust the spacing, which was a few px off, so that could have made it look off.
